// Auth for Login and Registration
export const CLIENT_LOADED = "CLIENT_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Clients
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";
export const GET_CLIENTS_START = "GET_CLIENTS_START";
export const GET_CLIENTS_FAILURE = "GET_CLIENTS_FAILURE";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const CLIENTS_ERROR = "CLIENTS_ERROR";
export const GET_CLIENT_INFO = "GET_CLIENT_INFO";
export const CLIENT_LOGIN_SUCCESS = "CLIENT_LOGIN_SUCCESS";

export const EMAIL_REQUEST_SUCCESS = "EMAIL_REQUEST_SUCCESS";
export const EMAIL_REQUEST_FAILURE = "EMAIL_REQUEST_FAILURE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE";

export const UPDATE_METRIC_START = "UPDATE_METRIC_START";
export const UPDATE_METRIC_SUCCESS = "UPDATE_METRIC_SUCCESS";
export const UPDATE_METRIC_FAILURE = "UPDATE_METRIC_FAILURE";
export const GET_METRICS_START = "GET_METRICS_START";
export const GET_METRICS_SUCCESS = "GET_METRICS_SUCCESS";
export const GET_METRICS_FAILURE = "GET_METRICS_FAILURE";
export const GET_UPCOMING_SESSIONS = "GET_UPCOMING_SESSIONS"
// Coach

export const GET_RECORDS_START = "GET_RECORDS_START";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";
export const GET_COACH_INFO = "GET_COACH_INFO";
// get list of unassigned clients
export const GET_UNASSIGNED_CLIENTS = 'GET_UNASSIGNED_CLIENTS';
export const ASSIGN_CLIENT = 'ASSIGN_CLIENT';
// get list of clients for CoachDashboard
export const GET_CLIENT_SESSIONS = 'GET_CLIENT_SESSIONS'
export const GET_CLIENT_GOALS = 'GET_CLIENT_GOALS';
//get client coach
export const GET_MY_COACH = 'GET_MY_COACH';
export const GET_CLIENT_LIST_START = "GET_CLIENT_LIST_START";
export const GET_CLIENT_LIST_SUCCESS = "GET_CLIENT_LIST_SUCCESS";
export const GET_CLIENT_LIST_FAILURE = "GET_CLIENT_LIST_FAILURE";
export const UPDATE_SELECTED_CLIENT = "UPDATE_SELECTED_CLIENT";
export const GET_TEXT_START = "GET_TEXTS_START";
export const GET_TEXT_SUCCESS = "GET_TEXTS_SUCCESS";
export const ADD_TEXT_START = "ADD_TEXTS_START";
export const ADD_TEXT_SUCCESS = "ADD_TEXTS_SUCCESS";
export const GET_CHECKIN = "GET_CHECKIN";
export const GET_CLIENT_GOALS_SUCCESS = "GET_CLIENT_GOALS_SUCCESS";
export const GET_CLIENT_GOALS_FAILURE = "GET_CLIENT_GOALS_FAILURE";
export const GET_CLIENT_GOAL_SUCCESS = "GET_GOAL_SUCCESS";
export const GET_CLIENT_GOAL_FAILURE = "GET_GOAL_FAILURE";
export const UPDATE_SELECTED_CLIENT_GOAL = "UPDATE_SELECTED_CLIENT_GOAL";
export const ADD_CLIENT_GOAL_SUCCESS = "ADD_CLIENT_GOAL_SUCCESS";
export const ADD_CLIENT_GOAL_FAILURE = "ADD_CLIENT_GOAL_FAILURE";
export const UPDATE_CLIENT_GOAL_SUCCESS = "UPDATE_CLIENT_GOAL_SUCCESS";
export const UPDATE_CLIENT_GOAL_FAILURE = "UPDATE_CLIENT_GOAL_FAILURE";
export const DELETE_CLIENT_GOAL_SUCCESS = "DELETE_CLIENT_GOAL_SUCCESS";
export const DELETE_CLIENT_GOAL_FAILURE = "DELETE_CLIENT_GOAL_FAILURE";

// coach schedule messages
export const ADD_SCHEDULE_MESSAGE_START = "ADD_SCHEDULE_MESSAGE_START";
export const ADD_SCHEDULE_MESSAGE_SUCCESS = "ADD_SCHEDULE_MESSAGE_SUCCESS";
export const GET_SCHEDULE_MESSAGE_START = "GET_SCHEDULE_MESSAGE_START";
export const GET_SCHEDULE_MESSAGE_SUCCESS = "GET_SCHEDULE_MESSAGE_SUCCESS";
export const DELETE_SCHEDULE_MESSAGE_START = "DELETE_SCHEDULE_MESSAGE_START";
export const DELETE_SCHEDULE_MESSAGE_SUCCESS =
	"DELETE_SCHEDULE_MESSAGE_SUCCESS";
export const UPDATE_SCHEDULE_MESSAGE_START = "UPDATE_SCHEDULE_MESSAGE_START";
export const UPDATE_SCHEDULE_MESSAGE_SUCCESS =
	"UPDATE_SCHEDULE_MESSAGE_SUCCESS";

export const COACH_ERROR = "COACH_ERROR";