// Auth for Login and Registration
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLIENT_LOADED = 'CLIENT_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Clients
export const GET_CLIENTS_START = 'GET_CLIENTS_START';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';
export const ADD_CLIENT = 'ADD_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const CLIENTS_ERROR = 'CLIENTS_ERROR';
export const CLIENTS_ERROR = 'CLIENTS_ERROR';
export const UPDATE_METRIC_START = 'UPDATE_METRIC_START';
export const UPDATE_METRIC_SUCCESS = 'UPDATE_METRIC_SUCCESS';
export const UPDATE_METRIC_FAILURE = 'UPDATE_METRIC_FAILURE';
